Upgrade to Helmet 4
freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game pull request #10
Opened 2021-03-19 03:17 UTC by SethFalco

I believe the main reasons this project is stuck using Helmet 3 specifically is because of the following breaking changes:
1. `helmet.noCache()` was removed.
2. Support for a fake powered by string was removed.

Please let me know if there are any other reasons Helmet was held back.

### `helmet.noCache()`
> **This functionality isn't going away. It's just moving to a separate module, `nocache`. You can find it [on npm](https://www.npmjs.com/package/nocache) and [on GitHub](https://github.com/helmetjs/nocache).**
> \- https://github.com/helmetjs/helmet/issues/215

I've added the dependency `nocache` to the project, the syntax has just changed a little but this can still be achieved with Helmet 4.

### `X-Powered-By`
This relates to the following issue and pull request.
Issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/40476
Pull Request: https://github.com/freeCodeCamp/freeCodeCamp/pull/40900

> `helmet.hidePoweredBy` removes the `X-Powered-By` header, which is set by default in some frameworks (like Express). Removing the header offers very limited security benefits (see [this discussion](https://github.com/expressjs/express/pull/2813#issuecomment-159270428)) and is mostly removed to save bandwidth.
> \- https://helmetjs.github.io/

On the same page, it's recommended not to use `app.use(helmet.hidePoweredBy())` and instead opt for `app.disable("x-powered-by")`, anyway. 

I updated the test to only verify that the `x-powered-by` header isn't equal to `Express`, this logic is stolen from a challenge before the projects.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet.hidepoweredby.md#--hints--

2021-03-19 19:42 UTC, SethFalco commented
Converting this to a draft, as it seems I made a mistake.

I thought I had tested this properly, but made a mistake, `app.use(helmet.xssFilter());` now **disables** XSS filtering. This results in the `x-xss-protection` header being set to `0`.

Related:
https://github.com/helmetjs/helmet/issues/230
https://github.com/expressjs/expressjs.com/pull/1248

> Although these protections are largely unnecessary in modern browsers when sites implement a strong [`Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) that disables the use of inline JavaScript (`'unsafe-inline'`), they can still provide protections for users of older web browsers that don't yet support [CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP).

> * Chrome has removed their XSS Auditor
> * Firefox has not, and will not implement X-XSS-Protection
> * Edge has retired their XSS filter
>
> This means that if you do not need to support legacy browsers, it is recommended that you use Content-Security-Policy without allowing unsafe-inline scripts instead.
> \- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

I think this test should be replaced with using an appropriate Content Security Policy instead that doesn't allow `unsafe-inline` in JavaScript at least. I'll update this PR later.

2021-04-07 11:01 UTC, gikf commented
From my understanding changing this project to work on Helmet 4, would also require updating learning parts of curriculum related to Helmet.

2021-04-30 11:37 UTC, huyenltnguyen requested changes
Hey @SethFalco, thank you for the PR!

Since this is a major change and we are still discussing on it in https://github.com/freeCodeCamp/freeCodeCamp/pull/41527, I will have to temporarily block this one to avoid accidental merge.

2021-05-06 07:37 UTC, raisedadead commented
Closing as discussed in the parent PR on the main repo.

2021-05-06 07:37 UTC, closed without merging